### ISSUE TITLE
Add "Files" section to the top of all READMEs

### ISSUE THREAD

**Issue by coolaj86** [webinstall/webi-installers#660]
## Who could make a PR for this?

This can be done all at once by one person, or a little at a time by many people.

## Knowledge Needed to do this

- Basic Markdown
- Basic git - clone, branch, push
- Basic command line - how to `npm run fmt`, etc

## Task to be Done

Each of the READMEs (the Cheat Sheets) should have a **Files** section at the top, right below the _update or switch versions_ instruction.

Files section should include:
- `~/.config/envman/PATH.env` (because it's always modified)
- `~/.local/bin/THING` or `~/.local/opt/THING` (depending on its `PATH`)
- any config files (e.g. `~/.config/THING.conf`)
- other files or folders created by the install process, or the initialization of the program (e.g. `~/.local/share/var/postgres/`)

## What the result looks like

~~~mkdn

To update or switch versions, run `webi THE_THING@stable` (or `@v1.1`, `@beta`,
etc).

### Files

```text
~/.bashrc
~/.config/envman/PATH.env
~/.local/bin/rg
~/.local/opt/rg/
~/.local/opt/rg-{version}/
```
~~~

## Progress

- Don't yet have a `### Files` section \
   (note: the ones with an `alias` in the header don't need one)
- [ ] [_examples/built-with-goreleaser/README.md](https://github.com/webinstall/webi-installers/blob/main/_examples/built-with-goreleaser/README.md)
    - [ ] [_examples/compressed-with-xz/README.md](https://github.com/webinstall/webi-installers/blob/main/_examples/compressed-with-xz/README.md)
    - [ ] [_vim-example/README.md](https://github.com/webinstall/webi-installers/blob/main/_vim-example/README.md)
    - [x] [archiver/README.md](https://github.com/webinstall/webi-installers/blob/main/archiver/README.md)
    - [x] [awless/README.md](https://github.com/webinstall/webi-installers/blob/main/awless/README.md)
    - [x] [brew/README.md](https://github.com/webinstall/webi-installers/blob/main/brew/README.md)
    - [x] [caddy/README.md](https://github.com/webinstall/webi-installers/blob/main/caddy/README.md)
    - [ ] [chromedriver/README.md](https://github.com/webinstall/webi-installers/blob/main/chromedriver/README.md)
    - [x] [comrak/README.md](https://github.com/webinstall/webi-installers/blob/main/comrak/README.md)
    - [x] [curlie/README.md](https://github.com/webinstall/webi-installers/blob/main/curlie/README.md)
    - [ ] [dashmsg/README.md](https://github.com/webinstall/webi-installers/blob/main/dashmsg/README.md)
    - [ ] [deno/README.md](https://github.com/webinstall/webi-installers/blob/main/deno/README.md)
    - [x] [dotenv-linter/README.md](https://github.com/webinstall/webi-installers/blob/main/dotenv-linter/README.md)
    - [x] [dotenv/README.md](https://github.com/webinstall/webi-installers/blob/main/dotenv/README.md)
    - [x] ~~[duckdns/README.md](https://github.com/webinstall/webi-installers/blob/main/duckdns/README.md)~~ (_alias_)
    - [x] [fd/README.md](https://github.com/webinstall/webi-installers/blob/main/fd/README.md)
    - [x] [ffmpeg/README.md](https://github.com/webinstall/webi-installers/blob/main/ffmpeg/README.md)
    - [ ] [fish/README.md](https://github.com/webinstall/webi-installers/blob/main/fish/README.md)
    - [x] [flutter/README.md](https://github.com/webinstall/webi-installers/blob/main/flutter/README.md)
    - [x] [fzf/README.md](https://github.com/webinstall/webi-installers/blob/main/fzf/README.md)
    - [ ] [gh/README.md](https://github.com/webinstall/webi-installers/blob/main/gh/README.md)
    - [ ] [git-gpg-init/README.md](https://github.com/webinstall/webi-installers/blob/main/git-gpg-init/README.md)
    - [ ] [git/README.md](https://github.com/webinstall/webi-installers/blob/main/git/README.md)
    - [ ] [gitdeploy/README.md](https://github.com/webinstall/webi-installers/blob/main/gitdeploy/README.md)
    - [ ] [gitea/README.md](https://github.com/webinstall/webi-installers/blob/main/gitea/README.md)
    - [ ] [gnupg/README.md](https://github.com/webinstall/webi-installers/blob/main/gnupg/README.md)
    - [ ] [go-essentials/README.md](https://github.com/webinstall/webi-installers/blob/main/go-essentials/README.md)
    - [ ] [goreleaser/README.md](https://github.com/webinstall/webi-installers/blob/main/goreleaser/README.md)
    - [ ] [gprox/README.md](https://github.com/webinstall/webi-installers/blob/main/gprox/README.md)
    - [ ] [hexyl/README.md](https://github.com/webinstall/webi-installers/blob/main/hexyl/README.md)
    - [ ] [iterm-color-schemes/README.md](https://github.com/webinstall/webi-installers/blob/main/iterm-color-schemes/README.md)
    - [ ] [iterm-themes/README.md](https://github.com/webinstall/webi-installers/blob/main/iterm-themes/README.md)
    - [ ] [iterm-utils/README.md](https://github.com/webinstall/webi-installers/blob/main/iterm-utils/README.md)
    - [ ] [iterm/README.md](https://github.com/webinstall/webi-installers/blob/main/iterm/README.md)
    - [ ] [iterm2-color-schemes/README.md](https://github.com/webinstall/webi-installers/blob/main/iterm2-color-schemes/README.md)
    - [ ] [iterm2-themes/README.md](https://github.com/webinstall/webi-installers/blob/main/iterm2-themes/README.md)
    - [ ] [iterm2-utils/README.md](https://github.com/webinstall/webi-installers/blob/main/iterm2-utils/README.md)
    - [ ] [jq/README.md](https://github.com/webinstall/webi-installers/blob/main/jq/README.md)
    - [ ] [k9s/README.md](https://github.com/webinstall/webi-installers/blob/main/k9s/README.md)
    - [ ] [keypairs/README.md](https://github.com/webinstall/webi-installers/blob/main/keypairs/README.md)
    - [ ] [kind/README.md](https://github.com/webinstall/webi-installers/blob/main/kind/README.md)
    - [ ] [kubectx/README.md](https://github.com/webinstall/webi-installers/blob/main/kubectx/README.md)
    - [ ] [kubens/README.md](https://github.com/webinstall/webi-installers/blob/main/kubens/README.md)
    - [ ] [lf/README.md](https://github.com/webinstall/webi-installers/blob/main/lf/README.md)
    - [ ] [macos/README.md](https://github.com/webinstall/webi-installers/blob/main/macos/README.md)
    - [ ] [mutagen/README.md](https://github.com/webinstall/webi-installers/blob/main/mutagen/README.md)
    - [ ] [myip/README.md](https://github.com/webinstall/webi-installers/blob/main/myip/README.md)
    - [ ] [nerd-font/README.md](https://github.com/webinstall/webi-installers/blob/main/nerd-font/README.md)
    - [ ] [nerd-fonts/README.md](https://github.com/webinstall/webi-installers/blob/main/nerd-fonts/README.md)
    - [ ] [nerdfont/README.md](https://github.com/webinstall/webi-installers/blob/main/nerdfont/README.md)
    - [ ] [nerdfonts/README.md](https://github.com/webinstall/webi-installers/blob/main/nerdfonts/README.md)
    - [ ] [pandoc/README.md](https://github.com/webinstall/webi-installers/blob/main/pandoc/README.md)
    - [ ] [pathman/README.md](https://github.com/webinstall/webi-installers/blob/main/pathman/README.md)
    - [ ] [postgres/README.md](https://github.com/webinstall/webi-installers/blob/main/postgres/README.md)
    - [ ] [postgresql/README.md](https://github.com/webinstall/webi-installers/blob/main/postgresql/README.md)
    - [x] [powershell/README.md](https://github.com/webinstall/webi-installers/blob/main/powershell/README.md)
    - [x] [pwsh/README.md](https://github.com/webinstall/webi-installers/blob/main/pwsh/README.md)
    - [ ] [pyenv/README.md](https://github.com/webinstall/webi-installers/blob/main/pyenv/README.md)
    - [ ] [python3/README.md](https://github.com/webinstall/webi-installers/blob/main/python3/README.md)
    - [ ] [rclone/README.md](https://github.com/webinstall/webi-installers/blob/main/rclone/README.md)
    - [ ] [ripgrep/README.md](https://github.com/webinstall/webi-installers/blob/main/ripgrep/README.md)
    - [ ] [rust/README.md](https://github.com/webinstall/webi-installers/blob/main/rust/README.md)
    - [ ] [rustlang/README.md](https://github.com/webinstall/webi-installers/blob/main/rustlang/README.md)
    - [ ] [sass/README.md](https://github.com/webinstall/webi-installers/blob/main/sass/README.md)
    - [ ] [sclient/README.md](https://github.com/webinstall/webi-installers/blob/main/sclient/README.md)
    - [ ] [sd/README.md](https://github.com/webinstall/webi-installers/blob/main/sd/README.md)
    - [ ] [serviceman/README.md](https://github.com/webinstall/webi-installers/blob/main/serviceman/README.md)
    - [ ] [setcap-netbind/README.md](https://github.com/webinstall/webi-installers/blob/main/setcap-netbind/README.md)
    - [ ] [sqlpkg/README.md](https://github.com/webinstall/webi-installers/blob/main/sqlpkg/README.md)
    - [ ] [ssh-adduser/README.md](https://github.com/webinstall/webi-installers/blob/main/ssh-adduser/README.md)
    - [ ] [ssh-authorize/README.md](https://github.com/webinstall/webi-installers/blob/main/ssh-authorize/README.md)
    - [ ] [ssh-harden/README.md](https://github.com/webinstall/webi-installers/blob/main/ssh-harden/README.md)
    - [ ] [ssh-prohibit-password/README.md](https://github.com/webinstall/webi-installers/blob/main/ssh-prohibit-password/README.md)
    - [ ] [ssh-pubkey/README.md](https://github.com/webinstall/webi-installers/blob/main/ssh-pubkey/README.md)
    - [ ] [ssh-setpass/README.md](https://github.com/webinstall/webi-installers/blob/main/ssh-setpass/README.md)
    - [ ] [ssh-utils/README.md](https://github.com/webinstall/webi-installers/blob/main/ssh-utils/README.md)
    - [ ] [sshd-prohibit-password/README.md](https://github.com/webinstall/webi-installers/blob/main/sshd-prohibit-password/README.md)
    - [ ] [sttr/README.md](https://github.com/webinstall/webi-installers/blob/main/sttr/README.md)
    - [ ] [sudo/README.md](https://github.com/webinstall/webi-installers/blob/main/sudo/README.md)
    - [ ] [syncthing/README.md](https://github.com/webinstall/webi-installers/blob/main/syncthing/README.md)
    - [ ] [test/README.md](https://github.com/webinstall/webi-installers/blob/main/test/README.md)
    - [ ] [vcruntime/README.md](https://github.com/webinstall/webi-installers/blob/main/vcruntime/README.md)
    - [ ] [vim-ale/README.md](https://github.com/webinstall/webi-installers/blob/main/vim-ale/README.md)
    - [ ] [vim-beyondcode/README.md](https://github.com/webinstall/webi-installers/blob/main/vim-beyondcode/README.md)
    - [ ] [vim-devicons/README.md](https://github.com/webinstall/webi-installers/blob/main/vim-devicons/README.md)
    - [ ] [vim-go/README.md](https://github.com/webinstall/webi-installers/blob/main/vim-go/README.md)
    - [ ] [vim-gui/README.md](https://github.com/webinstall/webi-installers/blob/main/vim-gui/README.md)
    - [ ] [vim-lastplace/README.md](https://github.com/webinstall/webi-installers/blob/main/vim-lastplace/README.md)
    - [ ] [vim-leader/README.md](https://github.com/webinstall/webi-installers/blob/main/vim-leader/README.md)
    - [ ] [vim-nerdtree/README.md](https://github.com/webinstall/webi-installers/blob/main/vim-nerdtree/README.md)
    - [ ] [vim-rust/README.md](https://github.com/webinstall/webi-installers/blob/main/vim-rust/README.md)
    - [ ] [vim-sensible/README.md](https://github.com/webinstall/webi-installers/blob/main/vim-sensible/README.md)
    - [ ] [vim-syntastic/README.md](https://github.com/webinstall/webi-installers/blob/main/vim-syntastic/README.md)
    - [ ] [vim-viminfo/README.md](https://github.com/webinstall/webi-installers/blob/main/vim-viminfo/README.md)
    - [ ] [vim-whitespace/README.md](https://github.com/webinstall/webi-installers/blob/main/vim-whitespace/README.md)
    - [ ] [vps-addswap/README.md](https://github.com/webinstall/webi-installers/blob/main/vps-addswap/README.md)
    - [ ] [vps-utils/README.md](https://github.com/webinstall/webi-installers/blob/main/vps-utils/README.md)
    - [ ] [watchexec/README.md](https://github.com/webinstall/webi-installers/blob/main/watchexec/README.md)
    - [ ] [webi/README.md](https://github.com/webinstall/webi-installers/blob/main/webi/README.md)
    - [ ] [wsl/README.md](https://github.com/webinstall/webi-installers/blob/main/wsl/README.md)
    - [ ] [wsl1/README.md](https://github.com/webinstall/webi-installers/blob/main/wsl1/README.md)
    - [ ] [wsl2/README.md](https://github.com/webinstall/webi-installers/blob/main/wsl2/README.md)
    - [ ] [xz/README.md](https://github.com/webinstall/webi-installers/blob/main/xz/README.md)
    - [ ] [yq/README.md](https://github.com/webinstall/webi-installers/blob/main/yq/README.md)
    - [ ] [ziglang/README.md](https://github.com/webinstall/webi-installers/blob/main/ziglang/README.md)
    - [ ] [zoxide/README.md](https://github.com/webinstall/webi-installers/blob/main/zoxide/README.md)
- Have a `### Files`, but need double-checking
    - [ ] [_example/README.md](https://github.com/webinstall/webi-installers/blob/main/_example/README.md)
    - [ ] [aliasman/README.md](https://github.com/webinstall/webi-installers/blob/main/aliasman/README.md)
    - [ ] [arc/README.md](https://github.com/webinstall/webi-installers/blob/main/arc/README.md)
    - [ ] [atomicparsley/README.md](https://github.com/webinstall/webi-installers/blob/main/atomicparsley/README.md)
    - [x] [bat/README.md](https://github.com/webinstall/webi-installers/blob/main/bat/README.md)
    - [ ] [beyond-shell/README.md](https://github.com/webinstall/webi-installers/blob/main/beyond-shell/README.md)
    - [ ] [bun/README.md](https://github.com/webinstall/webi-installers/blob/main/bun/README.md)
    - [ ] [cmake/README.md](https://github.com/webinstall/webi-installers/blob/main/cmake/README.md)
    - [ ] [dashcore-utils/README.md](https://github.com/webinstall/webi-installers/blob/main/dashcore-utils/README.md)
    - [ ] [dashcore/README.md](https://github.com/webinstall/webi-installers/blob/main/dashcore/README.md)
    - [ ] [dashd/README.md](https://github.com/webinstall/webi-installers/blob/main/dashd/README.md)
    - [ ] [delta/README.md](https://github.com/webinstall/webi-installers/blob/main/delta/README.md)
    - [ ] [duckdns.sh/README.md](https://github.com/webinstall/webi-installers/blob/main/duckdns.sh/README.md)
    - [ ] [git-config-gpg/README.md](https://github.com/webinstall/webi-installers/blob/main/git-config-gpg/README.md)
    - [ ] [go/README.md](https://github.com/webinstall/webi-installers/blob/main/go/README.md)
    - [ ] [golang/README.md](https://github.com/webinstall/webi-installers/blob/main/golang/README.md)
    - [ ] [gpg-pubkey/README.md](https://github.com/webinstall/webi-installers/blob/main/gpg-pubkey/README.md)
    - [ ] [gpg/README.md](https://github.com/webinstall/webi-installers/blob/main/gpg/README.md)
    - [ ] [grype/README.md](https://github.com/webinstall/webi-installers/blob/main/grype/README.md)
    - [ ] [hugo-extended/README.md](https://github.com/webinstall/webi-installers/blob/main/hugo-extended/README.md)
    - [ ] [hugo/README.md](https://github.com/webinstall/webi-installers/blob/main/hugo/README.md)
    - [ ] [iterm2/README.md](https://github.com/webinstall/webi-installers/blob/main/iterm2/README.md)
    - [ ] [jshint/README.md](https://github.com/webinstall/webi-installers/blob/main/jshint/README.md)
    - [ ] [koji/README.md](https://github.com/webinstall/webi-installers/blob/main/koji/README.md)
    - [ ] [lsd/README.md](https://github.com/webinstall/webi-installers/blob/main/lsd/README.md)
    - [ ] [node/README.md](https://github.com/webinstall/webi-installers/blob/main/node/README.md)
    - [ ] [ots/README.md](https://github.com/webinstall/webi-installers/blob/main/ots/README.md)
    - [ ] [prettier/README.md](https://github.com/webinstall/webi-installers/blob/main/prettier/README.md)
    - [ ] [python/README.md](https://github.com/webinstall/webi-installers/blob/main/python/README.md)
    - [ ] [python2/README.md](https://github.com/webinstall/webi-installers/blob/main/python2/README.md)
    - [ ] [rg/README.md](https://github.com/webinstall/webi-installers/blob/main/rg/README.md)
    - [ ] [shellcheck/README.md](https://github.com/webinstall/webi-installers/blob/main/shellcheck/README.md)
    - [ ] [shfmt/README.md](https://github.com/webinstall/webi-installers/blob/main/shfmt/README.md)
    - [ ] [vim-airline-themes/README.md](https://github.com/webinstall/webi-installers/blob/main/vim-airline-themes/README.md)
    - [ ] [vim-airline/README.md](https://github.com/webinstall/webi-installers/blob/main/vim-airline/README.md)
    - [ ] [vim-commentary/README.md](https://github.com/webinstall/webi-installers/blob/main/vim-commentary/README.md)
    - [ ] [vim-essentials/README.md](https://github.com/webinstall/webi-installers/blob/main/vim-essentials/README.md)
    - [ ] [vim-italics/README.md](https://github.com/webinstall/webi-installers/blob/main/vim-italics/README.md)
    - [ ] [vim-prettier/README.md](https://github.com/webinstall/webi-installers/blob/main/vim-prettier/README.md)
    - [ ] [vim-shell/README.md](https://github.com/webinstall/webi-installers/blob/main/vim-shell/README.md)
    - [ ] [vim-shfmt/README.md](https://github.com/webinstall/webi-installers/blob/main/vim-shfmt/README.md)
    - [ ] [vim-smartcase/README.md](https://github.com/webinstall/webi-installers/blob/main/vim-smartcase/README.md)
    - [ ] [vim-spell/README.md](https://github.com/webinstall/webi-installers/blob/main/vim-spell/README.md)
    - [ ] [zig/README.md](https://github.com/webinstall/webi-installers/blob/main/zig/README.md)

**Comment by NohaFahmi** [comment]
Hi @coolaj86, can I work on this?

**Comment by coolaj86** [comment]
@NohaFahmi Yes.

You can pick things you're already familiar with or do a little research on each package to know if there's a config file or data dir.

Just comment with the ones you work on as you go.

**Comment by RubenRam** [comment]
Hi @coolaj86, I'd like to help as well. I'll be picking items from a to f, which are the following:

[archiver/README.md](https://github.com/webinstall/webi-installers/blob/main/archiver/README.md)
[awless/README.md](https://github.com/webinstall/webi-installers/blob/main/awless/README.md)
[brew/README.md](https://github.com/webinstall/webi-installers/blob/main/brew/README.md)
[caddy/README.md](https://github.com/webinstall/webi-installers/blob/main/caddy/README.md)
[chromedriver/README.md](https://github.com/webinstall/webi-installers/blob/main/chromedriver/README.md)
[comrak/README.md](https://github.com/webinstall/webi-installers/blob/main/comrak/README.md)
[curlie/README.md](https://github.com/webinstall/webi-installers/blob/main/curlie/README.md)
[dashmsg/README.md](https://github.com/webinstall/webi-installers/blob/main/dashmsg/README.md)
[deno/README.md](https://github.com/webinstall/webi-installers/blob/main/deno/README.md)
[dotenv-linter/README.md](https://github.com/webinstall/webi-installers/blob/main/dotenv-linter/README.md)
[dotenv/README.md](https://github.com/webinstall/webi-installers/blob/main/dotenv/README.md)
[duckdns/README.md](https://github.com/webinstall/webi-installers/blob/main/duckdns/README.md)
[fd/README.md](https://github.com/webinstall/webi-installers/blob/main/fd/README.md)
[ffmpeg/README.md](https://github.com/webinstall/webi-installers/blob/main/ffmpeg/README.md)
[fish/README.md](https://github.com/webinstall/webi-installers/blob/main/fish/README.md)
[flutter/README.md](https://github.com/webinstall/webi-installers/blob/main/flutter/README.md)
[fzf/README.md](https://github.com/webinstall/webi-installers/blob/main/fzf/README.md)

Hope that's fine with you, @NohaFahmi .

**Comment by coolaj86** [comment]
@RubenRam Do it!

**Comment by coolaj86** [comment]
@NohaFahmi @RubenRam Do y'all have a timeline of when I can expect a PR (or consider the request stale)?

**Comment by RubenRam** [comment]
@coolaj86, I've just sent a PR (#667) with most of the items. Some are missing due to some incompatibilities with Linux availability (e.g.: prompts to use OS package manager instead) or the packages not being not available from the website.

Here's the list of the progress:
- [x] archiver/README.md
- [x] awless/README.md
- [x] brew/README.md
- [x] caddy/README.md
- [ ] chromedriver/README.md
- [x] comrak/README.md
- [x] curlie/README.md
- [x] dashmsg/README.md
- [ ] deno/README.md
- [x] dotenv-linter/README.md
- [x] dotenv/README.md
- [] duckdns/README.md 
- [x] fd/README.md
- [x] ffmpeg/README.md
- [ ] fish/README.md
- [x] flutter/README.md
- [x] fzf/README.md

If the PR is accepted, and you're ok with it, I'll move on to items from g to m and we can review the items missing later on. I've pretty much automatized it so should be quicker this time.

**Comment by coolaj86** [comment]
@RubenRam I'm glad to hear you've automated much of it. See my edits and proceed to g-m. Thanks!
