### ISSUE TITLE
Cleanup Tasks for AJ

### ISSUE THREAD

**Issue by coolaj86** [webinstall/webi-installers#673]
- [x] webinstall/webi-installers#674 
- [x] webinstall/webi-installer-requests#66
- [x] ~~dotenv-linter v3 updates~~ https://github.com/webinstall/webi-installers/issues/251
