### ISSUE TITLE
[Installer] Add mv alias for Windows

### ISSUE THREAD

**Issue by coolaj86** [webinstall/webi-installers#92]
# Add `mv` cmd alias for Windows

We want to add `mv` as a cmd alias for `move`.

This is NOT LIKE MOST webi pages. It will be a copy of `sudo/` and NOT a copy of `example/`.

'install.ps1`:

```pwsh
#!/usr/bin/env pwsh

echo "Installing mv.cmd..."

# TODO Move-Item todo

# Add to path
& "$Env:USERPROFILE\.local\bin\pathman.exe" add ~/.local/bin

echo "Installed to '$Env:USERPROFILE\.local\bin\mv.cmd'"
echo ""
```

# How to create a webi installer

[![Video Tutorial: How to create a webi Installer](https://user-images.githubusercontent.com/122831/91064908-17f28100-e5ed-11ea-9cf0-ab3363cdf4f8.jpeg)](https://youtu.be/RDLyJtiyQHA)

## Skills required

- Basic Command Line knowledge (`mkdir`, `mv`, `ls`, `tar`, `unzip`, variables)

## Steps

1. Clone and setup the webi packages repo
   ```bash
   git clone git@github.com:webinstall/packages.git
   pushd packages/
   npm install
   ```
2. Copy the Windows sudo alias example:
   ```bash
   rsync -av _sudo/ mv/
   ```
   - [ ] find and replace to change the name
     - [ ] update `mv/install.sh`
     - [ ] update `mv/install.ps1` according to the instructions ABOVE ^^
3. Needs an updated tagline and cheat sheet
   - [ ] update `sudo/README.md`
     - [ ] tagline
     - [ ] Switch versions
     - [ ] description / summary
     - [ ] General pointers on usage (and perhaps "gotchas")

**Comment by coolaj86** [comment]
I haven't had the need for this in a while. Closing because I'm not sure it's really that useful.
